import fs from "fs";
const app=fs.readFileSync(new URL("../src/app.js",import.meta.url),"utf8");
const wic=fs.readFileSync(new URL("../src/systems/walk_in_cooler.js",import.meta.url),"utf8");
const adapter=fs.readFileSync(new URL("../src/knowledge/wic_fact_adapter.js",import.meta.url),"utf8");
let n=0;const ok=(x,m)=>{if(!x)throw Error(m);n++};
ok(app.includes('data-wic-context="operatingState"'),"operating-state UI");
ok(app.includes('data-wic-context="evaporatorPressureQuality"'),"evap pressure quality UI");
ok(app.includes('operatingState: snapshot.context.operatingState'),"state passed to Brain");
ok(app.includes('factRecords: adapted.factRecords || []'),"quality records passed to Brain");
ok(app.includes('["room", "door_infiltration"]'),"room evidence included in snapshot");
ok(app.includes('["controls", "contactor_coil"]'),"control evidence included in snapshot");
ok(wic.includes('"large_warm_load"'),"warm product field definition");
ok(wic.includes('"open_blown"'),"fuse field definition");
ok(adapter.includes('"FACT_SENSOR_DISAGREES_REFERENCE"'),"sensor disagreement adapter");
ok(adapter.includes('"FACT_SOLENOID_FLOW_CONTINUES_CLOSED"'),"pumpdown solenoid adapter");
ok(adapter.includes('quality:eq.toUpperCase()'),"suspect pressure degrades SH fact");
ok(app.includes("buildWicCaseEvidenceControls()"),"room/control evidence exposed in System Check");
ok(app.includes('data-observation-component="${component}"'),"case evidence uses canonical observation map");
ok(app.includes('"Establish the operating state first"'),"state-gate presentation");
ok(app.includes('"Verify a questionable measurement first"'),"measurement-quality presentation");
console.log(`BRAIN 2.0 UI BOUNDARY: ${n} assertions PASS`);
