import fs from 'node:fs';
import {evaluateHypotheses} from '../../src/knowledge/hypothesis_engine.js';
const J=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url),'utf8'));
const suite=J('./wic_challenge_cases_v3.json'),rules=J('../../data/knowledge/core/evidence_rules.json').items,relationships=J('../../data/knowledge/core/relationships.json').items,discriminators=J('../../data/knowledge/core/discriminators.json').items,checks=J('../../data/knowledge/core/checks.json').items,concepts=J('../../data/knowledge/core/concepts.json').items,guides=J('../../data/knowledge/core/field_guidance.json').items;
const labels=new Map(concepts.map(x=>[x.id,x.label||x.id])),cl=new Map(checks.map(x=>[x.id,x.label||x.prompt||x.id]));
const STOP=new Set('the a an is are was were be been being to of and or in on at for from with by this that it its as before after first then next should may can could would system check result possible indicated observed present problem fault condition issue evidence direct known normal operating stable cooling'.split(/\s+/));
const norm=s=>String(s||'').toLowerCase().replace(/txv\/eev/g,'txv').replace(/\bsh\b/g,'superheat').replace(/\bsc\b/g,'subcooling').replace(/noncondensables?/g,'noncondensable').replace(/excess refrigerant/g,'overcharge').replace(/pressures/g,'pressure').replace(/readings/g,'reading').replace(/\bfans\b/g,'fan').replace(/\boperates\b/g,'operate').replace(/\bruns\b/g,'run').replace(/[^a-z0-9]+/g,' ').trim();const toks=s=>new Set(norm(s).split(/\s+/).filter(x=>x.length>2&&!STOP.has(x)));function sim(a,b){const A=toks(a),B=toks(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.min(A.size,B.size)};const best=(s,a)=>a.reduce((m,x)=>Math.max(m,sim(s,x)),0);
function run(c){const facts=c.setup.facts||[],state=c.operating_state||'STABLE_COOLING';const r=evaluateHypotheses({facts,factRecords:[],rules,relationships,discriminators,checks,application:'APP_WIC',operatingState:state,configuration:['TXV']});const gs=[...guides].sort((a,b)=>(b.priority||0)-(a.priority||0)).filter(g=>(!g.operating_states?.length||g.operating_states.includes(state))&&(g.requires_all||[]).every(f=>facts.includes(f))&&(!g.requires_any?.length||g.requires_any.some(f=>facts.includes(f))));const actual=[...facts.map(x=>labels.get(x)||x),...r.conditions.map(x=>labels.get(x.id)||x.id),...r.diagnoses.map(x=>labels.get(x.candidate)||x.candidate),...r.hypotheses.map(x=>labels.get(x.candidate)||x.candidate),...gs.flatMap(x=>[x.heading||x.id,x.relationship||'',x.short_meaning||''])];const next=[cl.get(r.nextCheck)||'',...gs.flatMap(g=>[g.relationship||'',g.short_meaning||'',...(g.steps||[]).flatMap(x=>[x.action||'',x.record||''])])];let errors=[];const hs=best(c.expected.system_check_result,actual);if(hs<.34)errors.push(`headline intent ${hs.toFixed(2)}`);const fscores=c.expected.confirmed_findings.map(x=>best(x,actual));if(fscores.some(x=>x<.25))errors.push(`finding intent ${fscores.map(x=>x.toFixed(2)).join(',')}`);const ns=best(c.expected.next_action_check,next);if(ns<.20)errors.push(`next-action intent ${ns.toFixed(2)}`);for(const id of c.expected.required_diagnosis_ids||[])if(!r.diagnoses.some(x=>x.candidate===id))errors.push(`required diagnosis missing ${id}`);for(const id of c.expected.required_any_ids||[])if(!facts.includes(id)&&!r.conditions.some(x=>x.id===id)&&!r.diagnoses.some(x=>x.candidate===id))errors.push(`required semantic id missing ${id}`);
// Enforce common negative diagnostic assertions against actual supported diagnoses.
for(const ban of c.expected.must_not_conclude||[]){
  const b=norm(ban), forbidden=[];
  if(/diagnose low charge|proof of low charge|proof low charge|undercharge/.test(b)) forbidden.push('CAUSE_LOW_REFRIGERANT_CHARGE');
  if(/diagnose overcharge/.test(b)) forbidden.push('CAUSE_OVERCHARGE');
  if(/noncondensable/.test(b)) forbidden.push('CAUSE_NONCONDENSABLES');
  if(/compressor inefficiency/.test(b)) forbidden.push('CAUSE_COMPRESSOR_INEFFICIENCY');
  if(/evaporator fan failure|condemn the evaporator fan/.test(b)) forbidden.push('CAUSE_EVAP_FAN_FAILURE');
  if(/door infiltration/.test(b)) forbidden.push('CAUSE_AIR_INFILTRATION');
  if(forbidden.some(id=>r.diagnoses.some(x=>x.candidate===id))) errors.push(`forbidden diagnosis supported: ${ban}`);
}return {id:c.id,title:c.title,pass:!errors.length,errors,facts,state,conditions:r.conditions.map(x=>x.id),diagnoses:r.diagnoses.map(x=>x.candidate),nextCheck:r.nextCheck,activeGuides:gs.map(x=>x.id),headlineScore:hs,nextScore:ns,findingScores:fscores}}
const results=suite.cases.map(run),passed=results.filter(x=>x.pass).length,failed=results.length-passed;fs.writeFileSync(new URL('./challenge_3_brain_report.json',import.meta.url),JSON.stringify({suite:suite.suite_id,brain:'2.0.13',total:results.length,passed,failed,results},null,2));console.log(`WIC CHALLENGE 3 RUNNER v1.1: ${passed} PASS / ${failed} FAIL / ${results.length} TOTAL`);for(const x of results)console.log(`${x.pass?'PASS':'FAIL'} ${x.id} ${x.title}${x.pass?'':` :: ${x.errors.join('; ')}`}`);console.log('\nDetailed JSON report: tests\\challenge_validation\\challenge_3_brain_report.json');if(failed)process.exitCode=1;
