export const ENGINE_VERSION="0.8.0";
const W={STRONG_SUPPORT:4,SUPPORT:2,CONTRADICT:-3,STRONG_CONTRADICT:-6,EXCLUDE:-999};
function rawRule(rule,facts){let score=0,pos=0,excluded=false,requiredMissing=false,direct=false;const evidence=[];for(const e of rule.evidence||[]){const present=facts.has(e.fact);if(e.role==="REQUIRED"&&!present)requiredMissing=true;if(!present){evidence.push({...e,state:"UNKNOWN"});continue;}evidence.push({...e,state:"PRESENT"});if(e.role==="EXCLUDE")excluded=true;if(e.role==="STRONG_SUPPORT"||e.role==="SUPPORT")pos++;if(e.direct===true&&(e.role==="STRONG_SUPPORT"||e.role==="SUPPORT"))direct=true;if(e.role in W&&W[e.role]>-999)score+=W[e.role];}return{ruleId:rule.id,candidate:rule.candidate,score,pos,direct,excluded,requiredMissing,evidence};}
function classify(e){if(e.excluded)return"EXCLUDED";if(e.score<0)return"CONTRADICTED";if(e.requiredMissing||e.pos===0)return"UNKNOWN";return e.direct&&e.score>0?"SUPPORTED":e.score>0?"POSSIBLE":"UNKNOWN";}
function crossDiscriminate(items,facts){const by=new Map(items.map(x=>[x.candidate,{...x}]));const lc=by.get("CAUSE_LOW_REFRIGERANT_CHARGE");if(lc&&facts.has("FACT_SUBCOOLING_RETAINED")&&(facts.has("FACT_DRIER_TEMP_DROP")||facts.has("FACT_LIQUID_LINE_PRESSURE_DROP"))){lc.className="CONTRADICTED";lc.reason="Retained subcooling with localized liquid-line restriction evidence.";}return[...by.values()];}
function collapseHierarchy(supported,relationships){const pm=new Map((relationships||[]).filter(r=>r.relation==="SUBTYPE_OF").map(r=>[r.from,r.to]));const ids=new Set(supported.map(x=>x.candidate)),hide=new Set();for(const child of ids){let p=pm.get(child),seen=new Set();while(p&&!seen.has(p)){seen.add(p);if(ids.has(p))hide.add(p);p=pm.get(p);}}return supported.filter(x=>!hide.has(x.candidate));}
function inferConditions(facts,relationships){const m=new Map();for(const r of relationships||[]){if(r.relation!=="INDICATES"||!facts.has(r.from))continue;if(!m.has(r.to))m.set(r.to,{id:r.to,evidence:[],sources:new Set()});const x=m.get(r.to);x.evidence.push(r.from);for(const s of r.sources||[])x.sources.add(s);}return[...m.values()].map(x=>({...x,sources:[...x.sources]}));}
const unknown=(c,f)=>{
 const satisfied=(c?.satisfied_if_any||[]).some(x=>f.has(x));
 if(satisfied)return false;
 return (c?.produces||[]).some(x=>!f.has(x));
};
function scoreCheck(c,f,targets){if(!unknown(c,f))return-1;const miss=(c.produces||[]).filter(x=>!f.has(x));if(!miss.length)return-1;let s=0;for(const t of targets)for(const e of t.evidence||[])if(miss.includes(e.fact))s+=e.direct?6:e.role==="STRONG_SUPPORT"?3:e.role==="SUPPORT"?2:0;return s;}
function next(checks,discs,facts,supported,possible,conditions){const cond=new Set(conditions.map(x=>x.id));if(!supported.length)for(const d of discs||[]){if(!(d.trigger_conditions||[]).some(x=>cond.has(x)))continue;for(const id of d.preferred_checks||[]){const c=checks.find(x=>x.id===id);if(c&&unknown(c,facts))return id;}}if(!supported.length&&possible.length){const active=new Set(possible.map(x=>x.candidate));let best=null,n=1;for(const d of discs||[]){const k=(d.candidates||[]).filter(x=>active.has(x)).length;if(k>n){best=d;n=k;}}if(best)for(const id of best.preferred_checks||[]){const c=checks.find(x=>x.id===id);if(c&&unknown(c,facts))return id;}}if(!supported.length)return null;let best=null,bs=0;for(const c of checks){const s=scoreCheck(c,facts,supported);if(s>bs){best=c;bs=s;}}return best?best.id:null;}
export function evaluateKnowledge({facts=[],rules=[],relationships=[],discriminators=[],checks=[]}){const fs=new Set(facts);let items=rules.map(r=>{const e=rawRule(r,fs);return{...e,className:classify(e)};});items=crossDiscriminate(items,fs).sort((a,b)=>b.score-a.score);const supported=items.filter(x=>x.className==="SUPPORTED"),possible=items.filter(x=>x.className==="POSSIBLE"),contradicted=items.filter(x=>x.className==="CONTRADICTED"),excluded=items.filter(x=>x.className==="EXCLUDED"),diagnoses=collapseHierarchy(supported,relationships),conditions=inferConditions(fs,relationships);let resolution="INSUFFICIENT_DISCRIMINATING_EVIDENCE";if(diagnoses.length===1)resolution="SINGLE_SUPPORTED_CAUSE";else if(diagnoses.length>1)resolution="MULTIPLE_SUPPORTED_CAUSES";else if(conditions.length)resolution="SUPPORTED_SYSTEM_CONDITION";return{resolution,conditions,diagnoses,supported,possible,contradicted,excluded,nextCheck:next(checks,discriminators,fs,diagnoses,possible,conditions),candidates:items};}
